language: python

sudo: false

python:
    - 3.6

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

before_script: cd site/

script:
    - nikola build --no-continue --strict
