language: python

sudo: false

python:
    - 3.6

cache: pip

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

before_script: cd site/

script:
    - nikola build --no-continue --strict

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: site/output
  target-branch: master
  github_token: $github_token
  on:
    branch: devel

